name: firebase_messaging
description: Flutter plugin for Firebase Cloud Messaging, a cross-platform
  messaging solution that lets you reliably deliver messages on Android and iOS.
homepage: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging
version: 9.0.0-1.0.nullsafety.0

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: ">=1.12.13+hotfix.5 <2.0.0"

dependencies:
  firebase_core: ">=0.8.0-1.0.nullsafety.0 <0.8.0-2.0.nullsafety.0"
  firebase_core_platform_interface: ">=4.0.0-1.0.nullsafety.0 <4.0.0-2.0.nullsafety.0"
  firebase_messaging_platform_interface: ">=2.0.0-1.0.nullsafety.0 <2.0.0-2.0.nullsafety.0"
  firebase_messaging_web: ">=0.2.0-1.0.nullsafety.0 <0.2.0-2.0.nullsafety.0"
  flutter:
    sdk: flutter
  meta: ^1.3.0-nullsafety.6

dev_dependencies:
  async: ^2.5.0-nullsafety.3
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0-nullsafety.2
  plugin_platform_interface: ^1.1.0-nullsafety.1
  test: any

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebase.messaging
        pluginClass: FlutterFirebaseMessagingPlugin
      ios:
        pluginClass: FLTFirebaseMessagingPlugin
      macos:
        pluginClass: FLTFirebaseMessagingPlugin
      web:
        default_package: firebase_messaging_web
